[workspace]
resolver = "3"
members = ["crucible", "crucible-core", "crucible-protocol", "crucible-proxy", "crucible-worker"]
exclude = ["examples"]

[workspace.package]
edition = "2024"
authors = ["Stuart Bruce"]
publish = false
# FIXME: Decide on licensing
license = "UNLICENSED"

[workspace.lints.rust]
unsafe_op_in_unsafe_fn = "warn"

[workspace.lints.clippy]
all = { level = "warn", priority = -1 }
pedantic = { level = "warn", priority = -1 }
undocumented_unsafe_blocks = "warn"

[workspace.dependencies]
base64 = "0.22"
bollard = "0.21"
clap = { version = "4", features = ["derive", "env"] }
futures-util = "0.3"
libc = "0.2"
postcard = { version = "1", default-features = false }
rand = "0.10"
reqwest = { version = "0.13", default-features = false, features = ["rustls", "json"] }
serde = { version = "1", features = ["derive"] }
serde_json = "1"
sqlx = { version = "0.9", default-features = false, features = ["runtime-tokio", "tls-rustls", "mysql"] }
strum = { version = "0.28", features = ["derive"] }
thiserror = "2"
tokio = { version = "1", features = ["fs", "io-util", "macros", "net", "process", "rt-multi-thread", "sync", "time"] }
tracing = "0.1"
tracing-subscriber = { version = "0.3", features = ["env-filter"] }
