[package]
name = "crucible-proxy"
version = "0.1.0"
edition.workspace = true
authors.workspace = true
publish.workspace = true
license.workspace = true

[dependencies]
clap = { workspace = true }
crucible-protocol = { path = "../crucible-protocol" }
serde_json = { workspace = true }
thiserror = { workspace = true }
tokio = { workspace = true, features = ["signal"] }
tracing = { workspace = true }
tracing-subscriber = { workspace = true }

[lints]
workspace = true
